# Generated by Django 5.2.4 on 2025-08-07 08:45

import community.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_sitestatistics_tag_post_review_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='post_attachments/', validators=[community.utils.validators.validate_file_size, community.utils.validators.validate_file_extension, community.utils.validators.validate_file_content], verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[community.utils.validators.validate_file_size, community.utils.validators.validate_image_extension, community.utils.validators.validate_file_content], verbose_name='头像'),
        ),
    ]
