# Generated by Django 5.2.4 on 2025-08-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_post_attachment_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='can_post_without_review',
        ),
    ]
