# Generated by Django 5.2.4 on 2025-08-08 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_remove_userprofile_can_post_without_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_moderate',
        ),
        migrations.AddField(
            model_name='comment',
            name='delete_reason',
            field=models.TextField(blank=True, verbose_name='删除原因'),
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_comments', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='post',
            name='delete_reason',
            field=models.TextField(blank=True, verbose_name='删除原因'),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_posts', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ban_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='封禁到期时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ban_reason',
            field=models.TextField(blank=True, verbose_name='封禁原因'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='封禁时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_users', to=settings.AUTH_USER_MODEL, verbose_name='封禁人'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='是否被封禁'),
        ),
    ]
